spring:
  datasource:
    url: jdbc:mysql://localhost:3308/members
    username : root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
